version: "3.5"

services:
  reverse_proxy:
    image: traefik:v2.5
    container_name: common_reverse_proxy
    volumes:
      - "./traefik:/etc/traefik"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    ports:
      - 80:80
      - 8080:8080

  common_redis:
    image: redis
    container_name: common_redis

networks:
  default:
    external:
      name: sharednetwork
